# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amazon_ups.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='amazon_ups.proto',
  package='',
  serialized_pb=_b('\n\x10\x61mazon_ups.proto\".\n\nAWarehouse\x12\n\n\x02id\x18\x01 \x02(\x05\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\"G\n\nASendTruck\x12\x18\n\x03whs\x18\x01 \x02(\x0b\x32\x0b.AWarehouse\x12\x1f\n\x08packages\x18\x02 \x03(\x0b\x32\r.APackageInfo\"N\n\x0c\x41PackageInfo\x12\x11\n\tpackageid\x18\x01 \x02(\x03\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\x12\x15\n\rups_user_name\x18\x04 \x01(\t\">\n\nUTruckSent\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x1f\n\x08packages\x18\x02 \x03(\x0b\x32\r.APackageInfo\" \n\rUTruckArrived\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\"B\n\x0e\x41StartDelivery\x12\x0f\n\x07truckid\x18\x01 \x02(\x05\x12\x1f\n\x08packages\x18\x02 \x03(\x0b\x32\r.APackageInfo\"\x1c\n\nUDelivered\x12\x0e\n\x06shipid\x18\x01 \x02(\x03\"\x1f\n\x0cUSendWorldID\x12\x0f\n\x07worldid\x18\x01 \x02(\x05\"W\n\x0c\x41toUCommands\x12\x1f\n\nsendtrucks\x18\x01 \x03(\x0b\x32\x0b.ASendTruck\x12&\n\rstartdelivery\x18\x02 \x03(\x0b\x32\x0f.AStartDelivery\"p\n\rUtoAResponses\x12\x1e\n\ttrucksent\x18\x01 \x03(\x0b\x32\x0b.UTruckSent\x12\x1f\n\x07\x61rrived\x18\x02 \x03(\x0b\x32\x0e.UTruckArrived\x12\x1e\n\tdelivered\x18\x03 \x03(\x0b\x32\x0b.UDelivered')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_AWAREHOUSE = _descriptor.Descriptor(
  name='AWarehouse',
  full_name='AWarehouse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AWarehouse.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='AWarehouse.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='AWarehouse.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=66,
)


_ASENDTRUCK = _descriptor.Descriptor(
  name='ASendTruck',
  full_name='ASendTruck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whs', full_name='ASendTruck.whs', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packages', full_name='ASendTruck.packages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=139,
)


_APACKAGEINFO = _descriptor.Descriptor(
  name='APackageInfo',
  full_name='APackageInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packageid', full_name='APackageInfo.packageid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='APackageInfo.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='APackageInfo.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ups_user_name', full_name='APackageInfo.ups_user_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=219,
)


_UTRUCKSENT = _descriptor.Descriptor(
  name='UTruckSent',
  full_name='UTruckSent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UTruckSent.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packages', full_name='UTruckSent.packages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=283,
)


_UTRUCKARRIVED = _descriptor.Descriptor(
  name='UTruckArrived',
  full_name='UTruckArrived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='UTruckArrived.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=317,
)


_ASTARTDELIVERY = _descriptor.Descriptor(
  name='AStartDelivery',
  full_name='AStartDelivery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truckid', full_name='AStartDelivery.truckid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packages', full_name='AStartDelivery.packages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=385,
)


_UDELIVERED = _descriptor.Descriptor(
  name='UDelivered',
  full_name='UDelivered',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shipid', full_name='UDelivered.shipid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=415,
)


_USENDWORLDID = _descriptor.Descriptor(
  name='USendWorldID',
  full_name='USendWorldID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='worldid', full_name='USendWorldID.worldid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=448,
)


_ATOUCOMMANDS = _descriptor.Descriptor(
  name='AtoUCommands',
  full_name='AtoUCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sendtrucks', full_name='AtoUCommands.sendtrucks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='startdelivery', full_name='AtoUCommands.startdelivery', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=537,
)


_UTOARESPONSES = _descriptor.Descriptor(
  name='UtoAResponses',
  full_name='UtoAResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trucksent', full_name='UtoAResponses.trucksent', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arrived', full_name='UtoAResponses.arrived', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delivered', full_name='UtoAResponses.delivered', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=651,
)

_ASENDTRUCK.fields_by_name['whs'].message_type = _AWAREHOUSE
_ASENDTRUCK.fields_by_name['packages'].message_type = _APACKAGEINFO
_UTRUCKSENT.fields_by_name['packages'].message_type = _APACKAGEINFO
_ASTARTDELIVERY.fields_by_name['packages'].message_type = _APACKAGEINFO
_ATOUCOMMANDS.fields_by_name['sendtrucks'].message_type = _ASENDTRUCK
_ATOUCOMMANDS.fields_by_name['startdelivery'].message_type = _ASTARTDELIVERY
_UTOARESPONSES.fields_by_name['trucksent'].message_type = _UTRUCKSENT
_UTOARESPONSES.fields_by_name['arrived'].message_type = _UTRUCKARRIVED
_UTOARESPONSES.fields_by_name['delivered'].message_type = _UDELIVERED
DESCRIPTOR.message_types_by_name['AWarehouse'] = _AWAREHOUSE
DESCRIPTOR.message_types_by_name['ASendTruck'] = _ASENDTRUCK
DESCRIPTOR.message_types_by_name['APackageInfo'] = _APACKAGEINFO
DESCRIPTOR.message_types_by_name['UTruckSent'] = _UTRUCKSENT
DESCRIPTOR.message_types_by_name['UTruckArrived'] = _UTRUCKARRIVED
DESCRIPTOR.message_types_by_name['AStartDelivery'] = _ASTARTDELIVERY
DESCRIPTOR.message_types_by_name['UDelivered'] = _UDELIVERED
DESCRIPTOR.message_types_by_name['USendWorldID'] = _USENDWORLDID
DESCRIPTOR.message_types_by_name['AtoUCommands'] = _ATOUCOMMANDS
DESCRIPTOR.message_types_by_name['UtoAResponses'] = _UTOARESPONSES

AWarehouse = _reflection.GeneratedProtocolMessageType('AWarehouse', (_message.Message,), dict(
  DESCRIPTOR = _AWAREHOUSE,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AWarehouse)
  ))
_sym_db.RegisterMessage(AWarehouse)

ASendTruck = _reflection.GeneratedProtocolMessageType('ASendTruck', (_message.Message,), dict(
  DESCRIPTOR = _ASENDTRUCK,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:ASendTruck)
  ))
_sym_db.RegisterMessage(ASendTruck)

APackageInfo = _reflection.GeneratedProtocolMessageType('APackageInfo', (_message.Message,), dict(
  DESCRIPTOR = _APACKAGEINFO,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:APackageInfo)
  ))
_sym_db.RegisterMessage(APackageInfo)

UTruckSent = _reflection.GeneratedProtocolMessageType('UTruckSent', (_message.Message,), dict(
  DESCRIPTOR = _UTRUCKSENT,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UTruckSent)
  ))
_sym_db.RegisterMessage(UTruckSent)

UTruckArrived = _reflection.GeneratedProtocolMessageType('UTruckArrived', (_message.Message,), dict(
  DESCRIPTOR = _UTRUCKARRIVED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UTruckArrived)
  ))
_sym_db.RegisterMessage(UTruckArrived)

AStartDelivery = _reflection.GeneratedProtocolMessageType('AStartDelivery', (_message.Message,), dict(
  DESCRIPTOR = _ASTARTDELIVERY,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AStartDelivery)
  ))
_sym_db.RegisterMessage(AStartDelivery)

UDelivered = _reflection.GeneratedProtocolMessageType('UDelivered', (_message.Message,), dict(
  DESCRIPTOR = _UDELIVERED,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UDelivered)
  ))
_sym_db.RegisterMessage(UDelivered)

USendWorldID = _reflection.GeneratedProtocolMessageType('USendWorldID', (_message.Message,), dict(
  DESCRIPTOR = _USENDWORLDID,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:USendWorldID)
  ))
_sym_db.RegisterMessage(USendWorldID)

AtoUCommands = _reflection.GeneratedProtocolMessageType('AtoUCommands', (_message.Message,), dict(
  DESCRIPTOR = _ATOUCOMMANDS,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:AtoUCommands)
  ))
_sym_db.RegisterMessage(AtoUCommands)

UtoAResponses = _reflection.GeneratedProtocolMessageType('UtoAResponses', (_message.Message,), dict(
  DESCRIPTOR = _UTOARESPONSES,
  __module__ = 'amazon_ups_pb2'
  # @@protoc_insertion_point(class_scope:UtoAResponses)
  ))
_sym_db.RegisterMessage(UtoAResponses)


# @@protoc_insertion_point(module_scope)
