# Generated by Django 2.2 on 2019-04-20 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField()),
                ('time1', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('time2', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('time3', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='truck_info',
            fields=[
                ('truck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='package_info',
            fields=[
                ('package_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('dest_x', models.FloatField()),
                ('dest_y', models.FloatField()),
                ('truck_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ups_website.truck_info')),
            ],
        
        options={
            'db_table': 'ups_db',
            'managed': True,
            },
        ),
    ]
