# Generated by Django 2.2 on 2019-04-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package_info',
            options={},
        ),
        migrations.AlterModelTable(
            name='package_info',
            table=None,
        ),
    ]
