# Generated by Django 2.2 on 2019-04-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_website', '0002_auto_20190420_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_info',
            name='package_status',
            field=models.CharField(choices=[('1', 'waiting for package'), ('2', 'out for delivery'), ('3', 'delivered')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='truck_info',
            name='truck_status',
            field=models.CharField(choices=[('1', 'idle'), ('2', 'travelling'), ('3', 'arrive warehouse'), ('4', 'loading'), ('5', 'delivering')], default='1', max_length=30),
        ),
    ]
