# Generated by Django 2.2 on 2019-04-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups_website', '0004_auto_20190422_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_info',
            name='package_status',
            field=models.CharField(choices=[('a', 'in warehouse'), ('b', 'out for delivery'), ('c', 'delivered')], default='a', max_length=30),
        ),
    ]
